osx_image: xcode7
language: objective-c
before_install:
  - brew reinstall xctool
  - gem install cocoapods
  - gem install slather
cache: cocoapods
script:
  - xctool -workspace MaxLeapGit.xcworkspace -scheme MaxLeapGit -sdk iphonesimulator build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - slather