platform :ios, '8.0'

pod 'CocoaLumberjack', '~> 2.0.1'
pod 'MagicalRecord', '~> 2.3.0'
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'WYPopoverController', '~> 0.2.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'HockeySDK', '~> 3.8.2'